[workspace]
members = [
    "crates/flow-plugin-fixture",
    "crates/flux-core",
    "crates/flux-launcher",
    "crates/flux-plugin-sdk",
    "crates/flux-plugin-example",
]
resolver = "2"

[workspace.package]
version = "0.1.102"
edition = "2021"
rust-version = "1.85"
license = "MIT"
authors = ["m1nuzz <m1nusz0r@gmail.com>"]
repository = "https://github.com/m1nuzz/flux-launcher"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-perf]
inherits = "release"
opt-level = 3
