[package]
name = "flux-launcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "A lightweight Windows launcher built with Rust and windui."

[dependencies]
flux-core = { path = "../flux-core" }
serde_json = "1"
windui = { path = "../../vendor/windui", default-features = false, features = ["d2d"] }
png = "0.17"

[target.'cfg(windows)'.dependencies]
everything-ipc = "0.1.4"
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Registry",
] }
